### ISSUE TITLE
Will you share the code for SMAC experiments?

### ISSUE THREAD

**Issue by jcformanek** [ZhengYinan-AIR/OMIGA#1]
Hi there, thanks for sharing your code for MAMuJoCo experiments. I was wondering if you plan to release the code to reproduce your experiments on SMAC?

**Comment by ZhengYinan-AIR** [comment]
Thank you for your attention. We are preparing and will release it as soon as possible

**Comment by RZ-Q** [comment]
Need code for SMAC tooooooooooooooo! (‾◡◝)

**Comment by ZhengYinan-AIR** [comment]
We have updated the SMAC code https://github.com/ZhengYinan-AIR/OMIGA/tree/SMAC

**Comment by RZ-Q** [comment]
Thanks for the update!

**Comment by RZ-Q** [comment]
Hello, I have a new question! I have download the dataset provided in https://github.com/ReinholdM/Offline-Pre-trained-Multi-Agent-Decision-Transformer , but those are all "good" level. However, the dataset you provided has all levels. Can you provide the whole dataset link or share other maps datasets?(cause your dataset only contains 4 maps)
Thanks!

**Comment by sanmuyang** [comment]
> Hello, I have a new question! I have download the dataset provided in https://github.com/ReinholdM/Offline-Pre-trained-Multi-Agent-Decision-Transformer , but those are all "good" level. However, the dataset you provided has all levels. Can you provide the whole dataset link or share other maps datasets?(cause your dataset only contains 4 maps)
> Thanks!

Our dataset is from MADT. Maybe you can directly ask the author of this paper for the original dataset. Their dataset is comprehensive.
