### ISSUE TITLE
Implementations about other compared algos.

### ISSUE THREAD

**Issue by RZ-Q** [ZhengYinan-AIR/OMIGA#2]
Hi!
In your paper, you compared OMIGA with BCQ-MA, CQL-MA, ICQ and OMAR. I have found the official implementations for ICQ-MA and OMAR, can you share your version for BCQ-MA and CQL-MA or just share the implementations link? This will help me a lot!
Thanks for your work!

**Comment by ZhengYinan-AIR** [comment]
We modified the code based on bcq and cql into a multi-agent version. You can view the official code of these two algorithms.
